apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nc-pod
  name: nc-pod
spec:
  selector:
    matchLabels:
      app: nc-pod
  template:
    metadata:
      labels:
        app: nc-pod
    spec:
      containers:
        - name: nc-pod
          image: knoxuser/nc-pod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nc-pod
  name: nc-svc
spec:
  ports:
  - name: "4444"
    port: 4444
    protocol: TCP
    targetPort: 4444
  - name: "8000"
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: "1389"
    port: 1389
    protocol: TCP
    targetPort: 1389
  selector:
    app: nc-pod
  type: LoadBalancer
status:
  loadBalancer: {}
